### ISSUE TITLE
Use with Kotlin

### ISSUE THREAD

**Issue by nieldw** [unbroken-dome/gradle-xjc-plugin#20]
This plugin doesn't work out of the box with Kotlin. 

To make your build pass, add the following to your (groovy) `build.gradle` file:

```
xjc {
    includeInMainCompilation = false
}

sourceSets {
    main { java { srcDir xjcGenerate.outputDirectory } }
}

compileKotlin {
    dependsOn xjcGenerate
}
```

Here's a working, complete `build.gradle` file assuming an XSD file in the default `src/main/schema` location: https://gist.github.com/nieldw/db9b46bebbfcf8c704a3b21d7e92fa01

**Comment by frost13it** [comment]
There is a simpler workaround:
```
sourceSets.main.java.srcDir(xjcGenerate)
```

It seems that generated sources are not visible from Kotlin side because of two issues:
1. The `xjcGenerate` task (instead of it's output directory) should be added to Java sources dirs. In this case it will be considered a dependency of `compileJava` and `compileKotlin` automatically.
It could be fixed [here](https://github.com/unbroken-dome/gradle-xjc-plugin/blob/6962122bbdc6dbd83ff5a0743e3e84a484e75ade/src/main/groovy/org/unbrokendome/gradle/plugins/xjc/XjcPlugin.groovy#L82) easily.
2. Kotlin plugin does not pick up Java source directories which added in `afterEvaluate { }` after it was applied.
I think it should be fixed in Kotlin plugin. As a workaround you can apply XJC plugin before Kotlin plugin.

**Comment by mdiskin** [comment]
I'm struggling to get this and the duplicate task in kotlin to work and keep getting NPE.

[guide to duplicate a task](https://stackoverflow.com/questions/60838336/gradle-kotlin-dsl-how-to-specify-duplicate-tasks)

**Comment by tkrullmann** [comment]
Version 2.0 is a complete rewrite in Kotlin, so Kotlin DSL support is now first class :-)
The plugin will also work on each source set by default, so this should no longer be an issue
